-- CreateEnum
CREATE TYPE "MusicalKey" AS ENUM ('C_MAJOR', 'C_SHARP_MAJOR', 'D_MAJOR', 'D_SHARP_MAJOR', 'E_MAJOR', 'F_MAJOR', 'F_SHARP_MAJOR', 'G_MAJOR', 'G_SHARP_MAJOR', 'A_MAJOR', 'A_SHARP_MAJOR', 'B_MAJOR', 'C_MINOR', 'C_SHARP_MINOR', 'D_MINOR', 'D_SHARP_MINOR', 'E_MINOR', 'F_MINOR', 'F_SHARP_MINOR', 'G_MINOR', 'G_SHARP_MINOR', 'A_MINOR', 'A_SHARP_MINOR', 'B_MINOR');

-- AlterTable
ALTER TABLE "Track" ADD COLUMN     "bpm" INTEGER,
ADD COLUMN     "key" "MusicalKey";
